# -*- coding: utf-8 -*-
"""ReliabilityWithFunctions (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JwhvatlFQofMOBgu7Hoh3MWIYE6d4GC
"""

import numpy as np

# Given the State Description Vector it returns a linear index number
def StateIndex(StateDescV, Dim, SetSize):
    #Function to linearize the state description
    Index = 0
    for i in range(Dim):
        Index += StateDescV[i]*((SetSize)**i)
    return int(Index)

# Given  a linear index number  it returns the State Description Vector
def StateDesc(Ind, Dim, SetSize):
    StateDescV = np.zeros(Dim,dtype=int)
    for i in range(Dim):
        StateDescV[i] = np.remainder(Ind,SetSize)
        Ind = np.floor_divide(Ind,SetSize)
    return StateDescV

def PreProcessing(alpha, K, C, Eps):
    DetSSize = K+1

    ProbReachingT = 1


    StateSpacesSize = DetSSize**C                               #Size of the state space for joint distribution
    TransitionM = np.zeros([StateSpacesSize,StateSpacesSize])
    DistributionV = np.zeros([1,StateSpacesSize])
    CondDistV = np.zeros(StateSpacesSize)
    ObsTransM= np.zeros([1,2])                                  #Transition Probabilities from Yellow States to Yellow or Red States at counter t(Row Number)

    NotRedMaskV = np.zeros(StateSpacesSize,dtype=int)
    NumberNonGreenV = np.zeros(StateSpacesSize,dtype=int)
    StateDescVector = np.zeros(C)

    #Begin Main Body

    # Create a list of Red State indices and a mask vector for non-red states
    RedList = []
    for Ind in range(StateSpacesSize):
        StateV = StateDesc(Ind,C,DetSSize)

        #Detect Red States
        RedState = 0
        for i in range(C):
            if StateV[i]==K:
                RedState = 1
                break

        if RedState==0:
            NotRedMaskV[Ind] = 1
        else:
            RedList.append(Ind)

        #Find Number of NonGreens

        NumNonGreen = 0
        for i in range(C):
            if StateV[i] !=0:
                NumNonGreen += 1

        NumberNonGreenV[Ind] = NumNonGreen



    #print("Number of States =",StateSpacesSize)
    #print("Not-Red Mask Vector =", NotRedMaskV)
    #print("Number of NonGreen Components Vector =", NumberNonGreenV)
    #print("List of Red States =", RedList)



    for FromInd in range(StateSpacesSize):
        FromStateV = StateDesc(FromInd,C,DetSSize)

        if NotRedMaskV[FromInd] == 0:
            TransitionM[FromInd,FromInd] =1         # Red States are modeled as absorbing
        else:
            for IncInd in range(2**C):
                IncV = StateDesc(IncInd,C,2)
                #print(IncInd,IncV)

                ToStateV = FromStateV+IncV
                ToStateInd = StateIndex(ToStateV,C,DetSSize)
                TransitionM[FromInd,ToStateInd]= (1-alpha)**(sum(IncV))*(alpha**(C-sum(IncV)))



    t=0
    DistributionV[t,:] = TransitionM[0,:]
    CondDistV = 1/(1-DistributionV[0,0])*DistributionV[t,:]
    CondDistV[0] = 0

    ObsTransM[0,:] = [1,0]

    DistributionV[t,:] = CondDistV


    #print(TransitionM)
    #print(DistributionV)


    while ProbReachingT > Eps:
    #for t in range(1,T):
        t += 1
        #DistributionV[t,:] = np.matmul(CondDistV,TransitionM)
        #print(DistributionV)
        #print(np.matmul(CondDistV,TransitionM))
        DistributionV = np.append(DistributionV, [np.matmul(CondDistV,TransitionM)], axis=0)
        #print(DistributionV)
        #print(DistributionV[t,:])
        CondDistV = np.multiply(DistributionV[t,:],NotRedMaskV)
        SumNotRed = np.sum(CondDistV)
        #ObsTransM[t,:] = [SumNotRed,1-SumNotRed]
        ObsTransM = np.append(ObsTransM, [[SumNotRed,1-SumNotRed]], axis=0)
        ProbReachingT *=  ObsTransM[t,0]
        CondDistV = 1/SumNotRed*CondDistV


    #print(DistributionV)
    #print(ObsTransM)
    #print('Prob', ProbReachingT)
    #print(ProbReachingT, t+1)

    return NumberNonGreenV, DistributionV, ObsTransM, t+1

NumberNonGreenV, DistributionV, ObsTransM, U = PreProcessing(.9, 3, 2, .1)
print(DistributionV)
print(ObsTransM)
print(U)

# !pip install gurobipy
import gurobipy as gp
#from gurobipy import GRB
#import itertools

import numpy as np


def ReliabilityLP(Code,K,C,U,alpha,cp,cc,cr,cu,co):
    DetSSize = K+1
    CounterStuckP = alpha**C
    ObsSTransProbMat = ObsTransM   #Rows are for the CounterState (SignalState is always NotRed); Colums are for the SignalState (CounterState is always increased by 1)
    StateSpacesSize = DetSSize**C                                 #Size of the state space for joint distribution

    PeriodCosts = np.zeros((2, U+1, C+1))
    PeriodCosts[0,:,1:C+1] = cp
    PeriodCosts[1,:,:] = cc

    for s in range(2):
        for n in range(0,U+1):     #   Check n
            for a in range(1, C+1):

                PeriodCosts[s,n,a] += ct*a

                if n == 0:
                  PeriodCosts[s,n,a] += (cr*NumberNonGreenV[0]+cu*max(NumberNonGreenV[0]-a,0)+co*max(-NumberNonGreenV[0]+a,0))

                else:
                  for Ind in range(StateSpacesSize):
                      PeriodCosts[s,n,a] += (cr*NumberNonGreenV[Ind]+cu*max(NumberNonGreenV[Ind]-a,0)+co*max(-NumberNonGreenV[Ind]+a,0))*DistributionV[n-1,Ind]




    #print(PeriodCosts)

    # Model
    lp = gp.Model("ReliabilityMDP")
    lp.setParam("FeasibilityTol", 1e-9)
    lp.setParam("NumericFocus", 2)

    #SignalSpace = range(2)                  # {NotRed, Red}
    #CounterSpace = range(U+1)               # {0,1, ... , U}
    DSpace = range(C+1)                     # {0,1, ... , C}

    P = lp.addMVar(shape=(2, U+1, C+1), name="P", obj=PeriodCosts)

    #Constraint 0  No invervention in state 0
    lp.addConstr(
        gp.quicksum(P[0,0,1:C+1])
        == 0)



    #Constraint 1
    lp.addConstr(
        gp.quicksum(P[0,0,:])
        -gp.quicksum(P[s,n,a]
            for s in range(2)
            for n in range(U+1)
            for a in range(1,C+1)
            )
        -CounterStuckP*P[0,0,0]
        == 0)

    #Constraint 2
    lp.addConstr(
        gp.quicksum(P[0,1,:])-
        (1-CounterStuckP)*P[0,0,0]
        == 0)

    #Constraint 3 and 4
    for n in range(2,U+1):
        lp.addConstr(
            gp.quicksum(P[0,n,:])-
            ObsSTransProbMat[n-1,0]*P[0,n-1,0]
            == 0)

        lp.addConstr(
            gp.quicksum(P[1,n,:])-
            ObsSTransProbMat[n-1,1]*P[0,n-1,0]
            == 0)

    #Constraint 5
    lp.addConstr(
        P.sum()
        == 1)

    #Constraint: In Red you have to intervene
    for n in range(U+1):
        lp.addConstr(
            P[1,n,0]
            == 0)

    #Constraint: You cannot reach Red State before the counter reaches K
    for n in range(K):
        for a in range(C+1):
            lp.addConstr(
                P[1,n,a]
                == 0)

    #Constraint: In Counter truncation point you have to intervene
    lp.addConstr(
        P[0,U,0]
        == 0)


    # If Code is 1 The Policy is intervene at K-1 taking optimal number of parts
    # If Code is 2 The Policy is intervene at K-1 taking only 1 part
    # If Code is 3 The Policy is intervene at K-1 taking C parts

    # If Code is 4 The Policy is intervene only at RED taking optimal number of parts
    # If Code is 5 The Policy is intervene only at RED taking only 1 part
    # If Code is 6 The Policy is intervene only at RED taking C parts



    if Code in [1,2,3]:
        for n in range(K-1):
            for a in range(1,C+1):
                lp.addConstr(
                    P[0,n,a]
                    == 0
                )
        lp.addConstr(
                P[0,K-1,0]
                ==0
        )

        if Code == 2:
            for a in range(2,C+1):
                lp.addConstr(
                    P[0,K-1,a]
                    ==0
                )
        elif Code == 3:
            for a in range(1,C):
                lp.addConstr(
                    P[0,K-1,a]
                    ==0
                )
    elif Code in [4,5,6]:
        for n in range(U):
            for a in range(1,C+1):
                lp.addConstr(
                    P[0,n,a]
                    ==0
                )
        if Code == 5:
            for n in range(U+1):
                for a in range(2,C+1):
                    lp.addConstr(
                        P[1,n,a]
                        ==0
                    )
        elif Code == 6:
            for n in range(U+1):
                for a in range(1,C):
                    lp.addConstr(
                        P[1,n,a]
                        ==0
                    )



    """
    lp.addConstr(P[0,0,1] == 0)
    lp.addConstr(P[0,0,2] == 0)
    """
    lp.optimize()
    SolutionMat = P.X
    Obj = lp.getObjective()
    ObjValue = Obj.getValue()
    #lp.display()
    return SolutionMat, ObjValue

# Scaling Experiments
import time

Eps = 0.001
alpha = .85

#KL = [ 3, 5, 7]
KL = [3]

#CL = [2, 3, 4, 5, 6]
CL= [2]

cp = 100               # Cost of Preventive Maintenance (Intervention cost at Yellow Signal)

cc = 400

ct = 0                  # Cost of transfering one component to maintenance site
cr = 50                  # Cost of replacing a non-Green component

cu = 100
co = 5                # Cost of returning an unused component at the end of intervention (return, overage)


for C in CL:
    for K in KL:

        print()
        print( "C =", C, "K =",K)
        start = time.time()

        NumberNonGreenV, DistributionV, ObsTransM, U = PreProcessing(alpha, K, C, Eps)

        end = time.time()
        print("Pre. Time =", end-start)
        print()

        DetSSize = K+1
        StateSpacesSize = DetSSize**C




        SolutionMat, Objective = ReliabilityLP(0,K,C,U,alpha,cp,cc,cr,cu,co)

print(SolutionMat)

Eps = 0.1                       # The sensitivity threshold for determining truncation point


#print(NumberNonGreenV)
#print(CounterStuckP)
#print(DistributionV)
#print(ObsTransM)
#print(U)


#alpha = 0.6             # Self transition probability
#K = 3                   # Last deterioration level (red)
#C = 2                   # Number of components
#U = T                   # Time Truncation Point

#cp = 50                 # Cost of Preventive Maintenance (Intervention cost at Yellow Signal)
#cc = 375                # Cost of Corrective Maintenance (Invervention cost at Red Signal)
#ct = 0                  # Cost of transfering one component to maintenance site
#cr = 0                  # Cost of replacing a non-Green component
#cu = 15                 # Cost of transfering a component after site visit (emergency, underage)
#co = 15                # Cost of returning an unused component at the end of intervention (return, overage)


#alphaL = [0.65, 0.75, 0.85, 0.95]
alphaL = [.85]
#KL = [ 3, 5, 7, 9]
KL = [2]
#CL = [1, 2, 4]
CL = [2]

#cp = 50                 # Cost of Preventive Maintenance (Intervention cost at Yellow Signal)
#cc = 375                # Cost of Corrective Maintenance (Invervention cost at Red Signal)
#ct = 0                  # Cost of transfering one component to maintenance site
#cr = 0                  # Cost of replacing a non-Green component
#cu = 15                  # Cost of transfering a component after site visit (emergency, underage)
#co = 15                # Cost of returning an unused component at the end of intervention (return, overage)

cpL = [100]                 # Cost of Preventive Maintenance (Intervention cost at Yellow Signal)
#ccL = [100, 200, 400, 800]                # Cost of Corrective Maintenance (Invervention cost at Red Signal)
ccL = [400]
ctL = [30]                  # Cost of transfering one component to maintenance site
crL = [50]                  # Cost of replacing a non-Green component
#cuL = [30, 60, 90]                  # Cost of transfering a component after site visit (emergency, underage)
cuL = [60]
coL = [30]                # Cost of returning an unused component at the end of intervention (return, overage)

import csv


DataFormat = [["alpha", "K", "C", "cp", "cc", "ct", "cr", "cu", "co", "U", "Z", "n*", "a*", "aREDmin", "Down", "Prevent", "EUnderage", "EOverage"]]

with open('ExperimentOutputs.csv', mode='w', newline='') as file:
    Writer = csv.writer(file)
    Writer.writerows(DataFormat)

DataFormatH = [["Code", "alpha", "K", "C", "cp", "cc", "ct", "cr", "cu", "co", "U", "Z", "n*", "a*", "aREDmin", "Down", "Prevent", "EUnderage", "EOverage"]]

with open('HeuristicExperimentOutputs.csv', mode='w', newline='') as file:
    Writer = csv.writer(file)
    Writer.writerows(DataFormatH)

for alpha in alphaL:
    for K in KL:
        for C in CL:
            NumberNonGreenV, DistributionV, ObsTransM, U = PreProcessing(alpha, K, C, Eps)
            DetSSize = K+1
            StateSpacesSize = DetSSize**C

            for cp in cpL:
                for cc in ccL:
                    for ct in ctL:
                        for cr in crL:
                            for cu in cuL:
                                for co in coL:
                                    for code in range(1):                       #Only the optimal policy
                                        SolutionMat, Objective = ReliabilityLP(code,K,C,U,alpha,cp,cc,cr,cu,co)
                                        Down = np.sum(SolutionMat[1,:,:])
                                        Prevent = np.sum(SolutionMat[0,:,1:C+1])

                                        EUnderage = 0
                                        EOverage = 0
                                        for s in range(2):
                                            for n in range(1,U+1):
                                                for a in range(1, C+1):

                                                    #PeriodCosts[s,n,a] += ct*a


                                                    for Ind in range(StateSpacesSize):
                                                        #[s,n,a] += (cr*NumberNonGreenV[Ind]+cu*max(NumberNonGreenV[Ind]-a,0)+co*max(-NumberNonGreenV[Ind]+a,0))*DistributionV[n-1,Ind]
                                                        EUnderage += max(NumberNonGreenV[Ind]-a,0)*DistributionV[n-1,Ind]*SolutionMat[s,n,a]
                                                        EOverage += max(-NumberNonGreenV[Ind]+a,0)*DistributionV[n-1,Ind]*SolutionMat[s,n,a]

                                        #print(Objective)
                                        #print(SolutionMat)
                                        Intervene, WithComp = np.nonzero(SolutionMat[0,:,1:C+1])


                                        WithComp += 1
                                        #print(Intervene, WithComp)
                                        #print(SolutionMat[:,:,0:C+1])

                                        aREDmin = 0
                                        for n in range(U+1):
                                            if sum(SolutionMat[1,n,1:C+1]) > 0:
                                                for a in range(1, C+1):
                                                    if SolutionMat[1,n,a] > 0:
                                                        aREDmin = a
                                                        break
                                                break


                                        if code == 0:
                                            if len(Intervene) == 1:

                                                DataFormat = [[alpha, K, C, cp, cc, ct, cr, cu, co, U, Objective, Intervene, WithComp, aREDmin, Down, Prevent, EUnderage, EOverage]]
                                                #print(DataFormat)

                                                with open('ExperimentOutputs.csv', mode='a', newline='') as file:
                                                    Writer = csv.writer(file)
                                                    Writer.writerows(DataFormat)

                                            else:

                                                DataFormat = [[alpha, K, C, cp, cc, ct, cr, cu, co, U, Objective, -1, -1, Down, Prevent, EUnderage, EOverage]]

                                                with open('ExperimentOutputs.csv', mode='a', newline='') as file:
                                                    Writer = csv.writer(file)
                                                    Writer.writerows(DataFormat)
                                        else:



                                            DataFormatH = [[code, alpha, K, C, cp, cc, ct, cr, cu, co, U, Objective, Intervene, WithComp, aREDmin, Down, Prevent, EUnderage, EOverage]]
                                            #print(Intervene, WithComp, aREDmin)

                                            with open('HeuristicExperimentOutputs.csv', mode='a', newline='') as file:
                                                Writer = csv.writer(file)
                                                Writer.writerows(DataFormatH)

